- become: true
  block:
    - name: Install python3,python3-pip
      ansible.builtin.apt:
        name: python3,python3-pip
        cache_valid_time: 3600

    - name: Create PiKi directory ({{ piki_dir }})
      ansible.builtin.file:
        path: "{{ piki_dir }}"
        state: directory
        owner: pi
        group: pi

- name: Copy PiKi files
  ansible.posix.synchronize:
    src: files/
    dest: "{{ piki_dir }}/"

- name: Setup PiKi virtualenv and dependencies
  ansible.builtin.pip:
    virtualenv: "{{ piki_dir }}/.venv"
    virtualenv_command: python3 -m venv
    name: "{{ piki_dir }}/piki"
    editable: true

- name: Create PiKi virtualenv bin symlinks
  ansible.builtin.file:
    src: "../.venv/bin/{{ item }}"
    path: "{{ piki_dir }}/bin/{{ item }}"
    state: link
  loop: [piki, piki-tty]

- name: Add PiKi bin to user path
  ansible.builtin.lineinfile:
    path: /home/pi/.profile
    line: PATH="{{ piki_dir }}/bin:$PATH"
  when: piki_add_bin_to_user_path

- become: true
  block:
    - name: Disable getty on /dev/tty1
      ansible.builtin.systemd_service:
        name: getty@tty1
        enabled: false
        state: stopped
      when: piki_disable_getty_tty1

    - name: Create piki-tty.service
      ansible.builtin.template:
        src: templates/piki-tty.service.j2
        dest: /etc/systemd/system/piki-tty.service
      when: piki_tty_enabled

    - name: Enable piki-tty.service
      ansible.builtin.systemd_service:
        name: piki-tty
        daemon_reload: true
        enabled: true
        state: restarted
      when: piki_tty_enabled
