- become: true
  block:
    - name: Create user services ({{ piki_user_services | length }})
      ansible.builtin.template:
        src: templates/piki-x.service.j2
        dest: "/etc/systemd/system/{{ piki_user_services_prefix }}{{ item.name }}.service"
      loop: "{{ piki_user_services }}"

    - name: Enable user services ({{ piki_user_services | length }})
      ansible.builtin.systemd_service:
        name: "{{ piki_user_services_prefix }}{{ item.name }}"
        daemon_reload: true
        enabled: true
        state: restarted
      loop: "{{ piki_user_services }}"
