- become: true
  block:
    - name: Install python3,python3-pip
      ansible.builtin.apt:
        name: python3,python3-pip
        cache_valid_time: 3600

    - name: Create PiKi directory ({{ piki_dir }})
      ansible.builtin.file:
        path: "{{ piki_dir }}"
        state: directory
        owner: pi
        group: pi

- name: Copy PiKi files
  ansible.posix.synchronize:
    src: files/
    dest: "{{ piki_dir }}/"

- name: Install PiKi requirements.txt
  ansible.builtin.pip:
    virtualenv: "{{ piki_dir }}/.venv"
    virtualenv_command: python3 -m venv
    requirements: "{{ piki_dir }}/piki/requirements.txt"

- become: true
  block:
    - name: Disable getty on /dev/tty1
      ansible.builtin.systemd_service:
        name: getty@tty1
        enabled: false
        state: stopped

    - name: Create piki-tty.service
      ansible.builtin.template:
        src: templates/piki-tty.service.j2
        dest: /etc/systemd/system/piki-tty.service

    - name: Enable piki-tty.service
      ansible.builtin.systemd_service:
        name: piki-tty
        daemon_reload: true
        enabled: true
        state: restarted
