- name: Install PiKi core
  ansible.builtin.include_tasks:
    file: install-core.yaml

- name: Install PiKi user services
  ansible.builtin.include_tasks:
    file: install-user-services.yaml
  when: piki_user_services | length > 0
