- name: "Loading stage tasks"
  ansible.builtin.include_tasks:
    file: stage-{{ piki_stage }}.yaml
  when: "(not piki_stage_start or piki_stage_index >= piki_stages.index(piki_stage_start)) and (not piki_stage_stop or piki_stage_index < piki_stages.index(piki_stage_stop))"
  loop: "{{ piki_stages }}"
  loop_control:
    loop_var: piki_stage
    index_var: piki_stage_index
