[project]
name = "piki"
version = "0.0.0"
requires-python = ">=3.11"
dependencies = [
    "click==8.1.8",
    "ioctl-opt==1.3",
    "evdev==1.9.1",
    "urwid==2.6.16",
    "toml==0.10.2",
]

[project.scripts]
piki-core = "piki.core.__main__:main"
piki-utils = "piki.utils.__main__:main"
